export const userData = {
  sid: "1",
  name: "Arnaud",
  submissions: [
    {
      id: 1,
      title:
        "MolE molecular representation through redundancy reduced embeddings",
      slug: "mole",
      description:
        "A deep learning model based on variational autoencoders that generates compact molecular representations by removing redundant features. Trained on 2.5 million compounds from ChEMBL and PubChem databases. Achieves 92% accuracy in molecular property prediction tasks and reduces embedding dimensionality by 60% while maintaining predictive performance across multiple downstream applications.",
      tags: ["ChEMBL", "Embedding", "Descriptor"],
      publication: "https://doi.org/10.1038/s42256-024-00812-3",
      sourceCode: "https://github.com/cheminformatics-lab/mole-embeddings",
      license: "MIT",
      submittedDate: "2024-03-15",
      status: "Approved",
    },
    {
      id: 2,
      title: "ChemFH chemical frequent hitter detection",
      slug: "chemfh",
      description:
        "Random forest classifier designed to identify promiscuous compounds that show activity across multiple unrelated assays. Trained on 450,000 screening results from PubChem BioAssay with balanced positive and negative examples. Model demonstrates 88% precision and 85% recall in detecting frequent hitters, helping prioritize genuine drug candidates over non-specific binders in early drug discovery.",
      tags: [
        "Drug-likeness",
        "Bioactivity profile",
        "Target identification",
        "ADME",
      ],
      publication: "https://doi.org/10.1021/acs.jcim.4c00156",
      sourceCode: "https://github.com/rodriguez-lab/chemfh-detector",
      license: "Apache-2.0",
      submittedDate: "2024-03-10",
      status: "Pending",
    },
    {
      id: 3,
      title: "ChemGPT-4.7",
      slug: "chemgpt-4-7",
      description:
        "Transformer-based generative model fine-tuned on 15 million SMILES strings from ZINC and ChEMBL databases. Capable of generating novel drug-like molecules with specified properties including solubility, permeability, and target affinity. Validation shows 78% of generated molecules pass Lipinski's rule of five and 65% exhibit predicted bioactivity against specified protein targets with novelty scores above 0.85.",
      tags: [
        "Chemical language model",
        "Compound generation",
        "ZINC",
        "Drug-likeness",
      ],
      publication: "https://arxiv.org/abs/2403.09847",
      sourceCode: "https://github.com/molgen-ai/chemgpt-4.7",
      license: "GPL-3.0-only",
      submittedDate: "2024-03-05",
      status: "Draft",
    },
    {
      id: 4,
      title: "Chemical Checker Signaturizer 3D D1-5",
      slug: "signaturizer-3d",
      description:
        "Convolutional neural network that generates molecular signatures from 3D conformations, capturing spatial features and pharmacophoric patterns. Trained on 1.8 million conformers from the COCONUT natural products database. Achieves superior performance in scaffold hopping tasks with 81% success rate in identifying bioisosteric replacements and demonstrates robust generalization across diverse chemical spaces.",
      tags: ["Natural product", "Embedding"],
      publication: "https://doi.org/10.1038/s41587-023-01881-x",
      sourceCode: "https://github.com/chemicalchecker/signaturizer-3d",
      license: "CC-BY-4.0",
      submittedDate: "2024-02-28",
      status: "Approved",
    },
    {
      id: 5,
      title: "Staphylococcus aureus activity prediction",
      slug: "s-aureus",
      description:
        "Gradient boosting classifier predicting antibacterial activity against methicillin-resistant Staphylococcus aureus strains. Trained on 125,000 compounds from the Community for Open Antimicrobial Drug Discovery database. Model achieves 89% accuracy with AUC-ROC of 0.94, successfully identifying novel scaffolds with minimum inhibitory concentrations below 10 μM in 73% of prospective validation experiments.",
      tags: ["S.aureus", "Antimicrobial activity", "MIC90", "ESKAPE"],
      publication: "https://doi.org/10.1128/AAC.01234-23",
      sourceCode: "https://github.com/antimicrobial-ml/staph-aureus-predictor",
      license: "BSD-3-Clause",
      submittedDate: "2024-02-28",
      status: "Draft",
    },
    {
      id: 6,
      title: "Antimicrobial class specificity prediction",
      slug: "antimicrobial-class",
      description:
        "Multi-class neural network classifier that predicts antimicrobial mechanism of action across seven major classes including cell wall synthesis inhibitors, protein synthesis inhibitors, and DNA replication disruptors. Trained on 95,000 annotated compounds from DrugBank and scientific literature. Achieves 84% overall accuracy with particularly strong performance in beta-lactam and quinolone classification at 91% and 88% respectively.",
      tags: ["Antimicrobial activity", "DrugBank", "Therapeutic indication"],
      publication: "https://doi.org/10.1016/j.cell.2024.01.015",
      sourceCode: "https://github.com/stokes-lab/antimicrobial-moa-classifier",
      license: "MIT",
      submittedDate: "2024-02-28",
      status: "Approved",
    },
    {
      id: 7,
      title: "Growth Inhibitors of Neisseria gonorrhoeae",
      slug: "n-gonorrhoeae",
      description:
        "Support vector machine model identifying compounds with growth inhibitory activity against antibiotic-resistant Neisseria gonorrhoeae strains. Trained on 68,000 screening results from the Medicines for Malaria Venture Pathogen Box and CDC surveillance data. Model demonstrates 86% sensitivity and 82% specificity, with validated hits showing IC50 values ranging from 2-15 μM against multi-drug resistant clinical isolates.",
      tags: ["Neglected tropical disease", "Antimicrobial activity", "IC50"],
      publication: "https://doi.org/10.1371/journal.pntd.0011892",
      sourceCode: "https://github.com/ntd-research/neisseria-inhibitors",
      license: "AGPL-3.0-only",
      submittedDate: "2024-02-28",
      status: "Pending",
    },
    {
      id: 8,
      title: "Antimalarial activity from OSM",
      slug: "antimalarial-osm",
      description:
        "Ensemble learning model combining random forests and neural networks to predict antimalarial activity against Plasmodium falciparum. Trained on 185,000 compounds from the Open Source Malaria project and MMV Malaria Box datasets. Achieves 90% accuracy in identifying sub-micromolar inhibitors with excellent correlation (R² = 0.87) between predicted and experimental IC50 values across multiple parasite life cycle stages.",
      tags: [
        "Malaria",
        "P.falciparum",
        "IC50",
        "Antimicrobial activity",
        "Neglected tropical disease",
      ],
      publication: "https://doi.org/10.1021/acs.jmedchem.3c02145",
      sourceCode: "https://github.com/opensourcemalaria/antimalarial-predictor",
      license: "CC0-1.0",
      submittedDate: "2024-02-28",
      status: "Pending",
    },
    {
      id: 9,
      title: "CYP3A4 metabolism",
      slug: "cyp3a4",
      description:
        "Deep neural network predicting substrate specificity and metabolic stability for the cytochrome P450 3A4 enzyme, responsible for metabolizing over 50% of marketed drugs. Trained on 220,000 experimental measurements from scientific literature and proprietary pharmaceutical databases. Model achieves 87% accuracy in substrate classification and predicts intrinsic clearance rates with mean absolute error of 0.32 log units.",
      tags: ["CYP450", "Metabolism", "ADME", "Human"],
      publication: "https://doi.org/10.1124/dmd.123.001456",
      sourceCode: "https://github.com/adme-models/cyp3a4-metabolism",
      license: "Apache-2.0",
      submittedDate: "2024-02-28",
      status: "Approved",
    },
    {
      id: 10,
      title: "S2DV HepG2 toxicity",
      slug: "s2dv-hepg2",
      description:
        "Graph convolutional network predicting hepatotoxicity using HepG2 cell line assay data as a surrogate for human liver toxicity. Trained on 142,000 compounds from the Tox21 and ToxCast programs with multi-endpoint toxicity annotations. Model achieves 83% balanced accuracy with 79% sensitivity for detecting hepatotoxic compounds, reducing false negatives by 25% compared to traditional QSAR approaches in prospective validation studies.",
      tags: ["Toxicity", "Tox21", "ToxCast"],
      publication: "https://doi.org/10.1021/acs.chemrestox.3c00389",
      sourceCode: "https://github.com/tox-prediction/s2dv-hepg2-toxicity",
      license: "BSD-2-Clause",
      submittedDate: "2024-02-28",
      status: "Draft",
    },
  ],
};
