export const METADATA_FORM_CFG = {
  task: ["Representation", "Annotation", "Sampling"],
  biomedicalArea: [
    "Any",
    "ADMET",
    "Antimicrobial resistance",
    "Malaria",
    "Tuberculosis",
    "COVID-19",
    "Gonorrhea",
    "Cancer",
    "Mycetoma",
    "AIDS",
    "Schistosomiasis",
    "Hepatitis",
    "Alzheimer",
    "Chagas",
    "Cryptosporidiosis",
    "Leprosy",
  ],
  subTask: [
    "Featurization",
    "Projection",
    "Property calculation or prediction",
    "Activity prediction",
    "Similarity search",
    "Generation",
  ],
  input: "Compound",
  inputDimension: 1,
  output: ["Compound", "Score", "Value", "Text"],
  outputConsistency: ["Fixed", "Variable"],
  license: [
    "MIT",
    "GPL-3.0-only",
    "GPL-3.0-or-later",
    "LGPL-3.0-only",
    "LGPL-3.0-or-later",
    "AGPL-3.0-only",
    "AGPL-3.0-or-later",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MPL-2.0",
    "CC-BY-3.0",
    "CC-BY-4.0",
    "CC0-1.0",
    "Proprietary",
    "None",
  ],
  tags: [
    "AIDS",
    "Alzheimer",
    "Cancer",
    "Cardiotoxicity",
    "Cytotoxicity",
    "COVID19",
    "Dengue",
    "Malaria",
    "Neglected tropical disease",
    "Schistosomiasis",
    "Tuberculosis",
    "A.baumannii",
    "E.coli",
    "E.faecium",
    "HBV",
    "HIV",
    "HDAC1",
    "Human",
    "K.pneumoniae",
    "Mouse",
    "M.tuberculosis",
    "P.aeruginosa",
    "P.falciparum",
    "N.gonorrhoeae",
    "Rat",
    "Sars-CoV-2",
    "S.aureus",
    "ESKAPE",
    "BACE",
    "CYP450",
    "GPCR",
    "hERG",
    "Fraction bound",
    "IC50",
    "Half-life",
    "LogD",
    "LogP",
    "LogS",
    "MIC90",
    "Molecular weight",
    "Papp",
    "pKa",
    "ADME",
    "Antimicrobial activity",
    "Antiviral activity",
    "Bioactivity profile",
    "Lipophilicity",
    "Metabolism",
    "Microsomal stability",
    "Natural product",
    "Price",
    "Quantum properties",
    "Permeability",
    "Side effects",
    "Solubility",
    "Synthetic accessibility",
    "Target identification",
    "Therapeutic indication",
    "Toxicity",
    "ChEMBL",
    "DrugBank",
    "MoleculeNet",
    "Tox21",
    "ToxCast",
    "TDCommons",
    "ZINC",
    "Chemical graph model",
    "Chemical language model",
    "Chemical notation",
    "Chemical synthesis",
    "Compound generation",
    "Descriptor",
    "Drug-likeness",
    "Embedding",
    "Fingerprint",
    "Similarity",
    "Biomedical text",
    "Mycetoma",
    "Antifungal activity",
    "Frequent hitter",
  ],
  deployment: ["Local", "Online"],
  publicationType: ["Peer reviewed", "Preprint", "Other"],
  source: ["Local", "Online"],
  sourceType: ["External", "Replicated", "Internal"],
  targetOrganism: [
    "Homo sapiens",
    "Mus musculus",
    "Rattus norvegicus",
    "Plasmodium falciparum",
    "Plasmodium vivax",
    "Mycobacterium tuberculosis",
    "Fast-acid bacteria",
    "Fungi",
    "Gram-negative bacteria",
    "Gram-positive bacteria",
    "Schistosoma mansoni",
    "Madurella mycetomatis",
    "Burkholderia cenocepacia",
    "Acinetobacter baumannii",
    "Neisseria gonorrhoeae",
    "Staphylococcus aureus",
    "Pseudomonas aeruginosa",
    "Enterobacteriaceae spp",
    "Enterococcus faecium",
    "Escherichia coli",
    "Helicobacter pylori",
    "Campylobacter spp",
    "Salmonella spp",
    "Streptococcus pneumoniae",
    "Haemophilus influenzae",
    "Shigella spp",
    "SARS-CoV-2",
    "SARS-CoV-1",
    "MERS",
    "Hepatitis B virus",
    "Hepatitis C virus",
    "HIV",
    "Ebola virus",
    "Any",
    "Klebsiella pneumoniae",
    "Akkermansia muciniphila",
    "Bacteroides caccae",
    "Bacteroides fragilis",
    "Bacteroides ovatus",
    "Bacteroides thetaiotaomicron",
    "Bacteroides uniformis",
    "Bacteroides vulgatus",
    "Bacteroides xylanisolvens",
    "Bifidobacterium adolescentis",
    "Bifidobacterium longum",
    "Bilophila wadsworthia",
    "Blautia obeum",
    "Clostridium bolteae",
    "Clostridium difficile",
    "Clostridium perfringens",
    "Clostridium ramosum",
    "Clostridium saccharolyticum",
    "Collinsella aerofaciens",
    "Coprococcus comes",
    "Dorea formicigenerans",
    "Eggerthella lenta",
    "Eubacterium eligens",
    "Eubacterium rectale",
    "Fusobacterium nucleatum",
    "Lactobacillus paracasei",
    "Odoribacter splanchnicus",
    "Parabacteroides distasonis",
    "Parabacteroides merdae",
    "Prevotella copri",
    "Roseburia hominis",
    "Roseburia intestinalis",
    "Ruminococcus bromii",
    "Ruminococcus gnavus",
    "Ruminococcus torques",
    "Streptococcus parasanguinis",
    "Streptococcus salivarius",
    "Veillonella parvula",
  ],
};
