export const METADATA_FORM_CFG = {
  tasks: ["Representation", "Annotation", "Sampling"],
  biomedicalArea: [
    "Any",
    "ADMET",
    "Antimicrobial resistance",
    "Malaria",
    "Tuberculosis",
    "COVID-19",
    "Gonorrhea",
    "Cancer",
    "Mycetoma",
    "AIDS",
    "Schistosomiasis",
    "Hepatitis",
    "Alzheimer",
    "Chagas",
    "Cryptosporidiosis",
    "Leprosy",
  ],
  subTasks: [
    "Featurization",
    "Projection",
    "Property calculation or prediction",
    "Activity prediction",
    "Similarity search",
    "Generation",
  ],
  input: "Compound",
  inputDimension: 1,
  output: ["Compound", "Score", "Value", "Text"],
  outputConsistency: ["Fixed", "Variable"],
  license: [
    "MIT",
    "GPL-3.0-only",
    "GPL-3.0-or-later",
    "LGPL-3.0-only",
    "LGPL-3.0-or-later",
    "AGPL-3.0-only",
    "AGPL-3.0-or-later",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MPL-2.0",
    "CC-BY-3.0",
    "CC-BY-4.0",
    "CC0-1.0",
    "Proprietary",
    "None",
  ],
  tags: [
    { value: "AIDS", label: "AIDS" },
    { value: "Alzheimer", label: "Alzheimer" },
    { value: "Cancer", label: "Cancer" },
    { value: "Cardiotoxicity", label: "Cardiotoxicity" },
    { value: "Cytotoxicity", label: "Cytotoxicity" },
    { value: "COVID19", label: "COVID19" },
    { value: "Dengue", label: "Dengue" },
    { value: "Malaria", label: "Malaria" },
    {
      value: "Neglected tropical disease",
      label: "Neglected tropical disease",
    },
    { value: "Schistosomiasis", label: "Schistosomiasis" },
    { value: "Tuberculosis", label: "Tuberculosis" },
    { value: "A.baumannii", label: "A.baumannii" },
    { value: "E.coli", label: "E.coli" },
    { value: "E.faecium", label: "E.faecium" },
    { value: "HBV", label: "HBV" },
    { value: "HIV", label: "HIV" },
    { value: "HDAC1", label: "HDAC1" },
    { value: "Human", label: "Human" },
    { value: "K.pneumoniae", label: "K.pneumoniae" },
    { value: "Mouse", label: "Mouse" },
    { value: "M.tuberculosis", label: "M.tuberculosis" },
    { value: "P.aeruginosa", label: "P.aeruginosa" },
    { value: "P.falciparum", label: "P.falciparum" },
    { value: "N.gonorrhoeae", label: "N.gonorrhoeae" },
    { value: "Rat", label: "Rat" },
    { value: "Sars-CoV-2", label: "Sars-CoV-2" },
    { value: "S.aureus", label: "S.aureus" },
    { value: "ESKAPE", label: "ESKAPE" },
    { value: "BACE", label: "BACE" },
    { value: "CYP450", label: "CYP450" },
    { value: "GPCR", label: "GPCR" },
    { value: "hERG", label: "hERG" },
    { value: "Fraction bound", label: "Fraction bound" },
    { value: "IC50", label: "IC50" },
    { value: "Half-life", label: "Half-life" },
    { value: "LogD", label: "LogD" },
    { value: "LogP", label: "LogP" },
    { value: "LogS", label: "LogS" },
    { value: "MIC90", label: "MIC90" },
    { value: "Molecular weight", label: "Molecular weight" },
    { value: "Papp", label: "Papp" },
    { value: "pKa", label: "pKa" },
    { value: "ADME", label: "ADME" },
    { value: "Antimicrobial activity", label: "Antimicrobial activity" },
    { value: "Antiviral activity", label: "Antiviral activity" },
    { value: "Bioactivity profile", label: "Bioactivity profile" },
    { value: "Lipophilicity", label: "Lipophilicity" },
    { value: "Metabolism", label: "Metabolism" },
    { value: "Microsomal stability", label: "Microsomal stability" },
    { value: "Natural product", label: "Natural product" },
    { value: "Price", label: "Price" },
    { value: "Quantum properties", label: "Quantum properties" },
    { value: "Permeability", label: "Permeability" },
    { value: "Side effects", label: "Side effects" },
    { value: "Solubility", label: "Solubility" },
    { value: "Synthetic accessibility", label: "Synthetic accessibility" },
    { value: "Target identification", label: "Target identification" },
    { value: "Therapeutic indication", label: "Therapeutic indication" },
    { value: "Toxicity", label: "Toxicity" },
    { value: "ChEMBL", label: "ChEMBL" },
    { value: "DrugBank", label: "DrugBank" },
    { value: "MoleculeNet", label: "MoleculeNet" },
    { value: "Tox21", label: "Tox21" },
    { value: "ToxCast", label: "ToxCast" },
    { value: "TDCommons", label: "TDCommons" },
    { value: "ZINC", label: "ZINC" },
    { value: "Chemical graph model", label: "Chemical graph model" },
    { value: "Chemical language model", label: "Chemical language model" },
    { value: "Chemical notation", label: "Chemical notation" },
    { value: "Chemical synthesis", label: "Chemical synthesis" },
    { value: "Compound generation", label: "Compound generation" },
    { value: "Descriptor", label: "Descriptor" },
    { value: "Drug-likeness", label: "Drug-likeness" },
    { value: "Embedding", label: "Embedding" },
    { value: "Fingerprint", label: "Fingerprint" },
    { value: "Similarity", label: "Similarity" },
    { value: "Biomedical text", label: "Biomedical text" },
    { value: "Mycetoma", label: "Mycetoma" },
    { value: "Antifungal activity", label: "Antifungal activity" },
    { value: "Frequent hitter", label: "Frequent hitter" },
  ],
  deployment: ["Local", "Online"],
  publicationType: ["Peer reviewed", "Preprint", "Other"],
  source: ["Local", "Online"],
  sourceType: ["External", "Replicated", "Internal"],
  targetOrganism: [
    "Homo sapiens",
    "Mus musculus",
    "Rattus norvegicus",
    "Plasmodium falciparum",
    "Plasmodium vivax",
    "Mycobacterium tuberculosis",
    "Fast-acid bacteria",
    "Fungi",
    "Gram-negative bacteria",
    "Gram-positive bacteria",
    "Schistosoma mansoni",
    "Madurella mycetomatis",
    "Burkholderia cenocepacia",
    "Acinetobacter baumannii",
    "Neisseria gonorrhoeae",
    "Staphylococcus aureus",
    "Pseudomonas aeruginosa",
    "Enterobacteriaceae spp",
    "Enterococcus faecium",
    "Escherichia coli",
    "Helicobacter pylori",
    "Campylobacter spp",
    "Salmonella spp",
    "Streptococcus pneumoniae",
    "Haemophilus influenzae",
    "Shigella spp",
    "SARS-CoV-2",
    "SARS-CoV-1",
    "MERS",
    "Hepatitis B virus",
    "Hepatitis C virus",
    "HIV",
    "Ebola virus",
    "Any",
    "Klebsiella pneumoniae",
    "Akkermansia muciniphila",
    "Bacteroides caccae",
    "Bacteroides fragilis",
    "Bacteroides ovatus",
    "Bacteroides thetaiotaomicron",
    "Bacteroides uniformis",
    "Bacteroides vulgatus",
    "Bacteroides xylanisolvens",
    "Bifidobacterium adolescentis",
    "Bifidobacterium longum",
    "Bilophila wadsworthia",
    "Blautia obeum",
    "Clostridium bolteae",
    "Clostridium difficile",
    "Clostridium perfringens",
    "Clostridium ramosum",
    "Clostridium saccharolyticum",
    "Collinsella aerofaciens",
    "Coprococcus comes",
    "Dorea formicigenerans",
    "Eggerthella lenta",
    "Eubacterium eligens",
    "Eubacterium rectale",
    "Fusobacterium nucleatum",
    "Lactobacillus paracasei",
    "Odoribacter splanchnicus",
    "Parabacteroides distasonis",
    "Parabacteroides merdae",
    "Prevotella copri",
    "Roseburia hominis",
    "Roseburia intestinalis",
    "Ruminococcus bromii",
    "Ruminococcus gnavus",
    "Ruminococcus torques",
    "Streptococcus parasanguinis",
    "Streptococcus salivarius",
    "Veillonella parvula",
  ],
};
