export const METADATA_FORM_CFG = {
  status: [{ value: "In Progress", label: "In Progress" }],
  tasks: [
    { value: "Representation", label: "Representation" },
    { value: "Annotation", label: "Annotation" },
    { value: "Sampling", label: "Sampling" },
  ],
  biomedicalArea: [
    { value: "Any", label: "Any" },
    { value: "ADMET", label: "ADMET" },
    { value: "Antimicrobial resistance", label: "Antimicrobial resistance" },
    { value: "Malaria", label: "Malaria" },
    { value: "Tuberculosis", label: "Tuberculosis" },
    { value: "COVID-19", label: "COVID-19" },
    { value: "Gonorrhea", label: "Gonorrhea" },
    { value: "Cancer", label: "Cancer" },
    { value: "Mycetoma", label: "Mycetoma" },
    { value: "AIDS", label: "AIDS" },
    { value: "Schistosomiasis", label: "Schistosomiasis" },
    { value: "Hepatitis", label: "Hepatitis" },
    { value: "Alzheimer", label: "Alzheimer" },
    { value: "Chagas", label: "Chagas" },
    { value: "Cryptosporidiosis", label: "Cryptosporidiosis" },
    { value: "Leprosy", label: "Leprosy" },
  ],
  subTasks: [
    { value: "Featurization", label: "Featurization" },
    { value: "Projection", label: "Projection" },
    {
      value: "Property calculation or prediction",
      label: "Property calculation or prediction",
    },
    { value: "Activity prediction", label: "Activity prediction" },
    { value: "Similarity search", label: "Similarity search" },
    { value: "Generation", label: "Generation" },
  ],
  inputs: [{ value: "Compound", label: "Compound" }],
  inputDimension: "1",
  outputs: [
    { value: "Compound", label: "Compound" },
    { value: "Score", label: "Score" },
    { value: "Value", label: "Value" },
    { value: "Text", label: "Text" },
  ],
  outputConsistencys: [
    { value: "Fixed", label: "Fixed" },
    { value: "Variable", label: "Variable" },
  ],
  licenses: [
    { value: "MIT", label: "MIT" },
    { value: "GPL-3.0-only", label: "GPL-3.0-only" },
    { value: "GPL-3.0-or-later", label: "GPL-3.0-or-later" },
    { value: "LGPL-3.0-only", label: "LGPL-3.0-only" },
    { value: "LGPL-3.0-or-later", label: "LGPL-3.0-or-later" },
    { value: "AGPL-3.0-only", label: "AGPL-3.0-only" },
    { value: "AGPL-3.0-or-later", label: "AGPL-3.0-or-later" },
    { value: "Apache-2.0", label: "Apache-2.0" },
    { value: "BSD-2-Clause", label: "BSD-2-Clause" },
    { value: "MPL-2.0", label: "MPL-2.0" },
    { value: "CC-BY-3.0", label: "CC-BY-3.0" },
    { value: "CC-BY-4.0", label: "CC-BY-4.0" },
    { value: "CC0-1.0", label: "CC0-1.0" },
    { value: "Proprietary", label: "Proprietary" },
    { value: "None", label: "None" },
  ],
  tags: [
    { value: "AIDS", label: "AIDS" },
    { value: "Alzheimer", label: "Alzheimer" },
    { value: "Cancer", label: "Cancer" },
    { value: "Cardiotoxicity", label: "Cardiotoxicity" },
    { value: "Cytotoxicity", label: "Cytotoxicity" },
    { value: "COVID19", label: "COVID19" },
    { value: "Dengue", label: "Dengue" },
    { value: "Malaria", label: "Malaria" },
    {
      value: "Neglected tropical disease",
      label: "Neglected tropical disease",
    },
    { value: "Schistosomiasis", label: "Schistosomiasis" },
    { value: "Tuberculosis", label: "Tuberculosis" },
    { value: "A.baumannii", label: "A.baumannii" },
    { value: "E.coli", label: "E.coli" },
    { value: "E.faecium", label: "E.faecium" },
    { value: "HBV", label: "HBV" },
    { value: "HIV", label: "HIV" },
    { value: "HDAC1", label: "HDAC1" },
    { value: "Human", label: "Human" },
    { value: "K.pneumoniae", label: "K.pneumoniae" },
    { value: "Mouse", label: "Mouse" },
    { value: "M.tuberculosis", label: "M.tuberculosis" },
    { value: "P.aeruginosa", label: "P.aeruginosa" },
    { value: "P.falciparum", label: "P.falciparum" },
    { value: "N.gonorrhoeae", label: "N.gonorrhoeae" },
    { value: "Rat", label: "Rat" },
    { value: "Sars-CoV-2", label: "Sars-CoV-2" },
    { value: "S.aureus", label: "S.aureus" },
    { value: "ESKAPE", label: "ESKAPE" },
    { value: "BACE", label: "BACE" },
    { value: "CYP450", label: "CYP450" },
    { value: "GPCR", label: "GPCR" },
    { value: "hERG", label: "hERG" },
    { value: "Fraction bound", label: "Fraction bound" },
    { value: "IC50", label: "IC50" },
    { value: "Half-life", label: "Half-life" },
    { value: "LogD", label: "LogD" },
    { value: "LogP", label: "LogP" },
    { value: "LogS", label: "LogS" },
    { value: "MIC90", label: "MIC90" },
    { value: "Molecular weight", label: "Molecular weight" },
    { value: "Papp", label: "Papp" },
    { value: "pKa", label: "pKa" },
    { value: "ADME", label: "ADME" },
    { value: "Antimicrobial activity", label: "Antimicrobial activity" },
    { value: "Antiviral activity", label: "Antiviral activity" },
    { value: "Bioactivity profile", label: "Bioactivity profile" },
    { value: "Lipophilicity", label: "Lipophilicity" },
    { value: "Metabolism", label: "Metabolism" },
    { value: "Microsomal stability", label: "Microsomal stability" },
    { value: "Natural product", label: "Natural product" },
    { value: "Price", label: "Price" },
    { value: "Quantum properties", label: "Quantum properties" },
    { value: "Permeability", label: "Permeability" },
    { value: "Side effects", label: "Side effects" },
    { value: "Solubility", label: "Solubility" },
    { value: "Synthetic accessibility", label: "Synthetic accessibility" },
    { value: "Target identification", label: "Target identification" },
    { value: "Therapeutic indication", label: "Therapeutic indication" },
    { value: "Toxicity", label: "Toxicity" },
    { value: "ChEMBL", label: "ChEMBL" },
    { value: "DrugBank", label: "DrugBank" },
    { value: "MoleculeNet", label: "MoleculeNet" },
    { value: "Tox21", label: "Tox21" },
    { value: "ToxCast", label: "ToxCast" },
    { value: "TDCommons", label: "TDCommons" },
    { value: "ZINC", label: "ZINC" },
    { value: "Chemical graph model", label: "Chemical graph model" },
    { value: "Chemical language model", label: "Chemical language model" },
    { value: "Chemical notation", label: "Chemical notation" },
    { value: "Chemical synthesis", label: "Chemical synthesis" },
    { value: "Compound generation", label: "Compound generation" },
    { value: "Descriptor", label: "Descriptor" },
    { value: "Drug-likeness", label: "Drug-likeness" },
    { value: "Embedding", label: "Embedding" },
    { value: "Fingerprint", label: "Fingerprint" },
    { value: "Similarity", label: "Similarity" },
    { value: "Biomedical text", label: "Biomedical text" },
    { value: "Mycetoma", label: "Mycetoma" },
    { value: "Antifungal activity", label: "Antifungal activity" },
    { value: "Frequent hitter", label: "Frequent hitter" },
  ],
  deployment: [
    { value: "Local", label: "Local" },
    { value: "Online", label: "Online" },
  ],
  publicationType: [
    { value: "Peer reviewed", label: "Peer reviewed" },
    { value: "Preprint", label: "Preprint" },
    { value: "Other", label: "Other" },
  ],
  source: [
    { value: "Online", label: "Online" },
    { value: "Local", label: "Local" },
  ],
  sourceType: [
    { value: "External", label: "External" },
    { value: "Replicated", label: "Replicated" },
    { value: "Internal", label: "Internal" },
  ],
  ttargetOrganism: [
    { value: "Homo sapiens", label: "Homo sapiens" },
    { value: "Mus musculus", label: "Mus musculus" },
    { value: "Rattus norvegicus", label: "Rattus norvegicus" },
    { value: "Plasmodium falciparum", label: "Plasmodium falciparum" },
    { value: "Plasmodium vivax", label: "Plasmodium vivax" },
    {
      value: "Mycobacterium tuberculosis",
      label: "Mycobacterium tuberculosis",
    },
    { value: "Fast-acid bacteria", label: "Fast-acid bacteria" },
    { value: "Fungi", label: "Fungi" },
    { value: "Gram-negative bacteria", label: "Gram-negative bacteria" },
    { value: "Gram-positive bacteria", label: "Gram-positive bacteria" },
    { value: "Schistosoma mansoni", label: "Schistosoma mansoni" },
    { value: "Madurella mycetomatis", label: "Madurella mycetomatis" },
    { value: "Burkholderia cenocepacia", label: "Burkholderia cenocepacia" },
    { value: "Acinetobacter baumannii", label: "Acinetobacter baumannii" },
    { value: "Neisseria gonorrhoeae", label: "Neisseria gonorrhoeae" },
    { value: "Staphylococcus aureus", label: "Staphylococcus aureus" },
    { value: "Pseudomonas aeruginosa", label: "Pseudomonas aeruginosa" },
    { value: "Enterobacteriaceae spp", label: "Enterobacteriaceae spp" },
    { value: "Enterococcus faecium", label: "Enterococcus faecium" },
    { value: "Escherichia coli", label: "Escherichia coli" },
    { value: "Helicobacter pylori", label: "Helicobacter pylori" },
    { value: "Campylobacter spp", label: "Campylobacter spp" },
    { value: "Salmonella spp", label: "Salmonella spp" },
    { value: "Streptococcus pneumoniae", label: "Streptococcus pneumoniae" },
    { value: "Haemophilus influenzae", label: "Haemophilus influenzae" },
    { value: "Shigella spp", label: "Shigella spp" },
    { value: "SARS-CoV-2", label: "SARS-CoV-2" },
    { value: "SARS-CoV-1", label: "SARS-CoV-1" },
    { value: "MERS", label: "MERS" },
    { value: "Hepatitis B virus", label: "Hepatitis B virus" },
    { value: "Hepatitis C virus", label: "Hepatitis C virus" },
    { value: "HIV", label: "HIV" },
    { value: "Ebola virus", label: "Ebola virus" },
    { value: "Any", label: "Any" },
    { value: "Klebsiella pneumoniae", label: "Klebsiella pneumoniae" },
    { value: "Akkermansia muciniphila", label: "Akkermansia muciniphila" },
    { value: "Bacteroides caccae", label: "Bacteroides caccae" },
    { value: "Bacteroides fragilis", label: "Bacteroides fragilis" },
    { value: "Bacteroides ovatus", label: "Bacteroides ovatus" },
    {
      value: "Bacteroides thetaiotaomicron",
      label: "Bacteroides thetaiotaomicron",
    },
    { value: "Bacteroides uniformis", label: "Bacteroides uniformis" },
    { value: "Bacteroides vulgatus", label: "Bacteroides vulgatus" },
    { value: "Bacteroides xylanisolvens", label: "Bacteroides xylanisolvens" },
    {
      value: "Bifidobacterium adolescentis",
      label: "Bifidobacterium adolescentis",
    },
    { value: "Bifidobacterium longum", label: "Bifidobacterium longum" },
    { value: "Bilophila wadsworthia", label: "Bilophila wadsworthia" },
    { value: "Blautia obeum", label: "Blautia obeum" },
    { value: "Clostridium bolteae", label: "Clostridium bolteae" },
    { value: "Clostridium difficile", label: "Clostridium difficile" },
    { value: "Clostridium perfringens", label: "Clostridium perfringens" },
    { value: "Clostridium ramosum", label: "Clostridium ramosum" },
    {
      value: "Clostridium saccharolyticum",
      label: "Clostridium saccharolyticum",
    },
    { value: "Collinsella aerofaciens", label: "Collinsella aerofaciens" },
    { value: "Coprococcus comes", label: "Coprococcus comes" },
    { value: "Dorea formicigenerans", label: "Dorea formicigenerans" },
    { value: "Eggerthella lenta", label: "Eggerthella lenta" },
    { value: "Eubacterium eligens", label: "Eubacterium eligens" },
    { value: "Eubacterium rectale", label: "Eubacterium rectale" },
    { value: "Fusobacterium nucleatum", label: "Fusobacterium nucleatum" },
    { value: "Lactobacillus paracasei", label: "Lactobacillus paracasei" },
    { value: "Odoribacter splanchnicus", label: "Odoribacter splanchnicus" },
    {
      value: "Parabacteroides distasonis",
      label: "Parabacteroides distasonis",
    },
    { value: "Parabacteroides merdae", label: "Parabacteroides merdae" },
    { value: "Prevotella copri", label: "Prevotella copri" },
    { value: "Roseburia hominis", label: "Roseburia hominis" },
    { value: "Roseburia intestinalis", label: "Roseburia intestinalis" },
    { value: "Ruminococcus bromii", label: "Ruminococcus bromii" },
    { value: "Ruminococcus gnavus", label: "Ruminococcus gnavus" },
    { value: "Ruminococcus torques", label: "Ruminococcus torques" },
    {
      value: "Streptococcus parasanguinis",
      label: "Streptococcus parasanguinis",
    },
    { value: "Streptococcus salivarius", label: "Streptococcus salivarius" },
    { value: "Veillonella parvula", label: "Veillonella parvula" },
  ],
};
