export const HELP_CFG = {
  basicIdentification: {
    section:
      "Essential identifiers for the model. The slug and title are how users will find and reference this model in the system.",
    title:
      "Provide a clear and descriptive title for your model. The title should be at least 70 characters long and convey the main purpose or function of the model. Avoid overly generic names and make sure it reflects the type of predictions or results the model produces.",
    slug: 'The slug is a short, easy-to-read version of your model\'s name used in URLs, all lowercase with words separated by dashes, like "predictive-cancer-analysis" for "Predictive Cancer Analysis."',
  },

  descriptionInterpretation: {
    section:
      "Detailed information about what the model does and how to understand its results. Explain the model's purpose, methodology, and how to interpret its predictions.",
    description:
      "Provide a brief overview of what your model does, what results it produces, and what kind of data was used to train it, just enough for someone to understand its purpose at a glance.",
    interpretation:
      "Explain in simple terms what the model's output means and how someone should read or understand the results, for example, whether a higher score indicates stronger activity or greater likelihood.",
  },

  classificationTags: {
    section:
      "Searchable labels that categorize the model. Select relevant tags from predefined categories to help users discover this model when searching by disease, organism, application, or other criteria.",
    tags: "Tags are keywords that describe the model's purpose, domain, or key features, helping users quickly find and categorize it.",
  },

  technicalSpecifications: {
    section:
      "Define the model's input/output behavior and machine learning task type. This section describes the technical characteristics of how the model processes data.",
    task: "Select the primary task that this model performs, such as classification, regression, or data generation. This helps categorize the model and guide users on its main purpose.",
    subtask:
      "Choose the specific subtask or variant of the primary task that this model handles.",
    input:
      "The input defines the type of data the model expects. Currently, all Ersilia models accept only Compound as input. This field is a string with only this single accepted value.",
    inputDimension:
      "This defines the input format expected by the model. Currently, all Ersilia models accept only 1 (numeric) as the input dimension. You can pass a list of inputs, but the model makes predictions one input at a time, not combined. This field only accepts this single integer value.",
    output:
      "The output defines the type of data produced by the model. Accepted output formats are: Score (e.g., a probability), Value (experimental value, molecular descriptor, or calculated property), Compound (a new compound generated by the model), Text (natural language output, e.g., a description). This field is a list, so multiple outputs can be selected.",
    outputDimension:
      "Defines the length of the output for each input, similar to the input dimension. This field accepts only a single integer value.",
    outputConsistency:
      "Indicates whether the model produces the same prediction for the same input. Fixed means predictions are always the same (typical for QSAR models), while Variable indicates predictions may change (common in generative models). This field only accepts a single string value.",
  },

  sourceLicensing: {
    section:
      "Attribution and legal information. Provide links to the original publication and code repository, along with licensing details and authorship information.",
    publicationUrl:
      "Provide the URL of the publication associated with this model. This could be a journal article, preprint, or conference paper that describes the methodology, datasets, and results. Including the publication helps users verify the model and understand its background.",
    publicationYear:
      "Enter the year in which the publication associated with this model was released. This helps users understand the timeline of the research and assess the relevance and recency of the model's methodology and results.",
    publicationType:
      "Select the type of publication associated with this model. This could be a peer-reviewed journal article, conference paper, preprint, technical report, or any other format that documents the model's methodology, results, and datasets. Providing this information helps users quickly identify the source and credibility of the model.",
    sourceUrl:
      "Provide the URL where the source code for this model is hosted. This could be a GitHub repository, GitLab project, or any other online code repository. Including the source code link helps users inspect the implementation, reproduce results, and understand the model's inner workings.",
    sourceType:
      "Specify the type of source for this model. Internal: Data or code maintained within the organization. External: Publicly available data or code from outside sources. Replicated: Data or models copied or reproduced from another source. Providing the correct source type helps users understand the origin and trustworthiness of the model.",
    license:
      "Choose the license under which this model is shared. Common options include AGPL, GPL, LGPL, etc. This determines how others can use, modify, or distribute the model and its code. For example, GPL allows redistribution but requires derived works to use the same license.",
    deployment:
      "Specify how this model is deployed. It can be Local, meaning it runs on a user's machine, or Online, meaning it is hosted on a server and accessed remotely.",
  },
  researchContext: {
    section:
      "Scientific domain and target organism information. Categorize the biomedical research area and specify which organisms (pathogens, hosts, or general applicability) the model relates to.",
    biomedicalArea:
      "Select the biomedical research areas relevant to this model. Examples include oncology, immunology, genomics, pharmacology, or neuroscience.",
    targetOrganism:
      "Select the organisms that this model is designed to study or affect. Examples could include human, mouse, bacterial strains, or other experimental organisms. Correctly specifying target organisms ensures appropriate use and interpretation of the model.",
  },
};
